events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            fastcgi_pass app:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/cgi-bin/app;
            fastcgi_param DOCUMENT_ROOT /var/www/html;
        }
    }
}
